### ISSUE TITLE
what google do I need to install?

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Converters#2]
I installed it, but it's not there. Any hints? I thought the makefile might have some, but I ran into another problem there... (see #3)

```
➜ pip install google
Collecting google
  Downloading google-3.0.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 2.1 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 4.7 MB/s
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.1-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4, google
Successfully installed beautifulsoup4-4.10.0 google-3.0.0 soupsieve-2.3.1

ValueSet-Converters on  master via 🐍 3.9.6 took 2s
➜ python -m value_set_vsac_to_json
Traceback (most recent call last):
  File "/Users/sigfried/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sigfried/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sigfried/bin/fetchvs/ValueSet-Converters/value_set_vsac_to_json/__main__.py", line 4, in <module>
    from value_set_vsac_to_json.interfaces.cli import cli
  File "/Users/sigfried/bin/fetchvs/ValueSet-Converters/value_set_vsac_to_json/interfaces/cli.py", line 8, in <module>
    from value_set_vsac_to_json.main import run
  File "/Users/sigfried/bin/fetchvs/ValueSet-Converters/value_set_vsac_to_json/main.py", line 15, in <module>
    from value_set_vsac_to_json.google_sheets import get_sheets_data
  File "/Users/sigfried/bin/fetchvs/ValueSet-Converters/value_set_vsac_to_json/google_sheets.py", line 24, in <module>
    from google.auth.exceptions import RefreshError
ModuleNotFoundError: No module named 'google'
```

**Comment by joeflack4** [comment]
This step, we were able to handle today via: `pip install -r requirements.txt`

Honestly I forgot to add this setup step to the readme xD. It's added now:

https://github.com/HOT-Ecosystem/ValueSet-Converters/#set-up--installation

---

Notes that... I realize now the setup might be a little weird because there are two "environment" directories; I wrote instructions for creating a directory called `venv` for the virtual environment, and a directory called `env` for the environmental variables and google sheet credentials files.

If you have suggestion for changing that let me know.
